# Generated by Django 4.2.13 on 2024-06-15 02:30

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nomb', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('idmember', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('idplan', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nomplan', models.CharField(max_length=200)),
                ('descriplan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('idtyplan', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('idplan', models.ForeignKey(on_delete=builtins.any, to='membresias.planes')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPlant',
            fields=[
                ('idclieplan', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('idcliente', models.ForeignKey(on_delete=builtins.any, to='membresias.clientes')),
                ('idplan', models.ForeignKey(on_delete=builtins.any, to='membresias.planes')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='idmember',
            field=models.ForeignKey(on_delete=builtins.any, to='membresias.membresia'),
        ),
        migrations.CreateModel(
            name='CellClient',
            fields=[
                ('idcell', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('telef', models.CharField(max_length=10)),
                ('idcliente', models.ForeignKey(on_delete=builtins.any, to='membresias.clientes')),
            ],
        ),
    ]
