# Generated by Django 4.2.13 on 2024-06-15 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellclient',
            name='idcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.clientes'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='idmember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.membresia'),
        ),
        migrations.AlterField(
            model_name='clientplant',
            name='idcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.clientes'),
        ),
        migrations.AlterField(
            model_name='clientplant',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.planes'),
        ),
        migrations.AlterField(
            model_name='tipoplan',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.planes'),
        ),
    ]
