# Generated by Django 5.0.6 on 2024-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0003_rename_telef_cellclient_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(default='changeme', max_length=15),
        ),
    ]
